In [4]:
# importação de arquivo
import pandas as pd
import numpy as np
# visualização de gráficos
import seaborn as sns
# visualização de gráficos
import matplotlib.pyplot as plt
# visualizar grafico dinâmico 
import plotly.express as px
# GaussianNB - Nome de uma distirbuição estatistica (usado para problemas genericos
from sklearn.naive_bayes import GaussianNB
import pickle

In [6]:
with open('./../base/risco_credito.pkl', 'rb') as f:
    X_risco_credit, y_risco_credit = pickle.load(f)

In [7]:
X_risco_credit.shape, y_risco_credit.shape

((14, 4), (14,))

In [8]:
X_risco_credit

array([[2, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 2],
       [1, 1, 1, 2],
       [1, 1, 0, 2],
       [2, 1, 1, 0],
       [2, 1, 0, 2],
       [0, 1, 1, 2],
       [0, 0, 0, 2],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 0, 1, 2],
       [2, 0, 1, 1]], dtype=object)

In [9]:
y_risco_credit

array(['alto', 'alto', 'moderado', 'alto', 'baixo', 'baixo', 'alto',
       'moderado', 'baixo', 'baixo', 'alto', 'moderado', 'baixo', 'alto'],
      dtype=object)

In [10]:
# vamos usar só alto e baixo e ignorar o moderado ara ficar alinhado com aula teoria
# axis = 0 - linha e 1 - coluna
X_risco_credit = np.delete(X_risco_credit, [2, 7, 11], axis=0)
y_risco_credit = np.delete(y_risco_credit, [2, 7, 11], axis=0)

In [11]:
from sklearn.linear_model import LogisticRegression

In [12]:
# treinamento (b0,b1,b2,b3)
logistic_risco_credit = LogisticRegression(random_state=1)
logistic_risco_credit.fit(X_risco_credit, y_risco_credit)

LogisticRegression(random_state=1)

In [13]:
# b0
logistic_risco_credit.intercept_

array([-0.80828993])

In [14]:
# b1,b2,b3,b4
logistic_risco_credit.coef_

array([[-0.76704533,  0.23906678, -0.47976059,  1.12186218]])

In [15]:
#  historia boa, divida alta, garantias nenhuma, renda > 35
#  historia ruim, divida alta, garantias adequada, renda < 15

predict = logistic_risco_credit.predict([[0,0,1,2], [2,0,0,0]])
predict

array(['baixo', 'alto'], dtype=object)